In [6]:
import numpy as np

### Numpy Data Types
Numpy has the following data types: 
- ```int```
- ```float```
- ```complex```
- ```bool```
- ```string```
- ```unicode```
- ```object```

The numeric data types have various precisions like 32-bit or 64-bit. 

Numpy data types can be represented using either __Type__ or __Type Code__

Data types can be defined at creating the numpy array and converted to other types later. 

You can use either _type, type code_ or _```np``` dot_ methods to define the data type of an array, but when you use ```np``` dot method to define the data type, it can only follow _type_ rather than _type code_.

In [7]:
arr=np.array([1,2,3],dtype='f4')     # f4 =float32
arr

array([1., 2., 3.], dtype=float32)

In [8]:
# Identical to the above
arr = np.array([1,2,3], dtype='float32')
arr.dtype

dtype('float32')

In [9]:
arr=np.array([1,2,"Ahmed"],dtype='f4')    #numpy can't convert 'Ahmed'(string) to float
arr.dtype

ValueError: could not convert string to float: 'Ahmed'

In [5]:
arr = np.array([1,2,"3.4"], dtype='float32')    #numpy can convert '3.4'(string) to float
arr.dtype

for i in arr:
    print(type(i))
    
print(arr[2]+3)

<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>
6.400000095367432


In [6]:
arr = np.array(["1","2","3"], dtype='int')
print(arr.dtype)

for i in arr:
    print(i)

int32
1
2
3


### Type Conversion

```astype``` method: convert the data type of an array to other data types. 

Notice that ```astype``` returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [7]:
arr = np.array([1,2,3], dtype='int16') # 16 / 8 = 2 ==> 2 bytes
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32) # convert arr type from int16 --> float32 ( 8 bytes )
print('Data Type After Conversion: ' + str(arr.dtype))
arr

Original Data Type: int16
Data Type After Conversion: float32


array([1., 2., 3.], dtype=float32)

__WARNING__: be cautious about data overflow when you downcast the data type (from higher precision to lower precision). Some unexpected and undefined values might occur and it is usually difficult to debug such issues. 

In [8]:
# An example of integer overflow at downcasting
arr = np.array([126,127,129], dtype='int16')

print('np array before type conversion: ' + str(arr))
#print(arr.max())
# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 129]
np array after type conversion: [ 126  127 -127]


### String and Unicode Data Type

The ```string_``` and ```unicode_``` data types are all implicitly _fixed-length_. 

The length of the string is given by their type code appended with a number. For example, ```S3``` represents string of length 3; ```U10``` represents unicode of length 10. Otherwise, the default length is the length of the longest string in the array.

If the length of a string in the array is shorter than the length of the data type defined or converted to, the string will be truncated.

In [9]:
# An example of truncated string
s = np.array(['a3c', 'd2fg'], dtype='S3')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'efghi'], dtype='U3')
print(s)

[b'a3c' b'd2f']
['abc' 'efg']


In [10]:
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest string in the array is "abc" and its length is 3.')

arr = np.array(['a', 'abc', 'abcd'], dtype=np.unicode_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest unicode in the array is "abcd" and its length is 4.')


The array is [b'a' b'ab' b'abc']
The data type is |S3 because the longest string in the array is "abc" and its length is 3.
The array is ['a' 'abc' 'abcd']
The data type is <U4 because the longest unicode in the array is "abcd" and its length is 4.


### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [11]:
mylist = [1,2,3,4,5]
arr = np.array(mylist)
print(arr)

l = [1,2,3,4,5]
print(l)

print(type(l))
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
int32


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [12]:
# np.arange(start, stop, step)
arr = np.arange(0, 21, 3)  
print(arr)
print(type(arr))

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [13]:
arr = np.random.rand(3,4)
print(arr)

[[0.8782061  0.53649492 0.52623968 0.16367243]
 [0.02997237 0.9511089  0.41830347 0.75598733]
 [0.82454797 0.88940009 0.09739854 0.45909511]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [14]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.int16)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0 0]
 [0 0]
 [0 0]]
Data Type: int16


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [16]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int32


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [18]:
full = np.full((4,4), 6)
print(full)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [19]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [20]:
# No axis specified, then flatten the input array first and repeat
# Data Augemnation 
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 4)) 

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]


In [21]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) # row 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [22]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))    

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [23]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [24]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [25]:
identity_matrix = np.eye(4)
#identity_matrix = identity_matrix.astype(int)
print(identity_matrix)
print(type(identity_matrix))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [26]:
identity_matrix = np.eye(3).astype(int)
#identity_matrix = identity_matrix.astype(int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=2) # default k = 0
print(identity_matrix)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
identity_matrix = np.identity(5)
print(identity_matrix)
print(type(identity_matrix))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


### Create an array with given values on the diagonal

In [29]:
arr = np.random.rand(5,5)
print(arr)
print("\n\n")
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.9077352  0.06711202 0.16210455 0.67865977 0.81034547]
 [0.25258544 0.10197168 0.59669968 0.44327104 0.83846988]
 [0.74978918 0.2886051  0.0352152  0.69552914 0.01768453]
 [0.93740486 0.87206448 0.79190021 0.81839287 0.91809036]
 [0.8093287  0.85974534 0.14084251 0.87041855 0.46132064]]



Values on the diagonal: [0.9077352  0.10197168 0.0352152  0.81839287 0.46132064]


In [30]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5,6])
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### Inspect an Array

In [31]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1f1ca752220
byteorder:  little
byteswap:  False
type: int64
None


In [32]:
print(arr.shape)

(2, 3)


In [33]:
print(len(arr)) # print number of rows 

2


In [34]:
print(arr.ndim)   #the number of dimensions of an array

2


In [35]:
print(arr.size)

6


In [36]:
threeD = np.array([  [[2,3] , [4,5]] , [[4,3],[2,8]]     ])
print(threeD.shape)
threeD.ndim

(2, 2, 2)


3

## Sampling Methods

In [37]:
# set seed
np.random.seed(50)
np.random.rand(3)
# another way 
#rs = np.random.RandomState(23)
#rs.rand(3)

array([0.49460165, 0.2280831 , 0.25547392])

In [38]:
# generate a random scalar
print(np.random.rand())

0.39632990972277693


In [39]:
# generate a random scalar
print(np.random.rand() * 10)   

3.77315097691124


In [40]:
# generate a random scalar
print(int(np.random.rand() * 10))

9


In [41]:
# generate a 2-D array
print(np.random.rand(3,3)) 

[[0.4081972  0.77189399 0.76053669]
 [0.31000935 0.3465412  0.35176482]
 [0.14546686 0.97266468 0.90917844]]


In [42]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[6 1 7]


In [43]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print()
print(np.random.random(10))
print()
print(np.random.ranf(10))
print()
print(np.random.sample(10))

[0.26465872 0.67136671 0.78927019 0.36441934 0.11342968 0.16679188
 0.01824974 0.78856948 0.27714299 0.86507366]

[0.52872064 0.69292202 0.05274132 0.77317277 0.20118524 0.01749162
 0.31797437 0.67441032 0.27666963 0.20606164]

[0.8856327  0.7314353  0.9259965  0.99136739 0.93596284 0.19035143
 0.15612517 0.89836939 0.45540685 0.29030955]

[0.21935083 0.6991026  0.52071031 0.27028162 0.90723576 0.95331391
 0.98321563 0.51788829 0.98754091 0.34743924]


In [44]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.3, 0.6]))

[2 2 0 0 2 1 2 2 2 2]


In [45]:
print(np.random.choice(3, 10))

[2 1 2 0 2 1 1 1 0 1]


### shuffle an array in place

In [46]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
np.random.shuffle(arr)
print(arr)

[4 1 9 2 5 7 8 0 6 3]


In [48]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
np.random.permutation(arr)

array([4, 6, 2, 0, 5, 9, 8, 7, 3, 1])

## Math Functions

In [49]:
arr = np.random.rand(5,5)
arr

array([[0.61323757, 0.29810165, 0.60237917, 0.42567684, 0.53854438],
       [0.48672986, 0.49989164, 0.91745948, 0.26287702, 0.04969769],
       [0.46269203, 0.40821902, 0.48704348, 0.07051578, 0.58210861],
       [0.9870218 , 0.20908846, 0.21237612, 0.96113505, 0.70695408],
       [0.59296821, 0.38085241, 0.6387405 , 0.50242857, 0.08979307]])

### element-wise addition, subtraction, multiplication and division

In [50]:
print(arr + 10)
print()
print(arr - 10)
print()
print(arr * 10)
print()
print(arr / 10)

[[10.61323757 10.29810165 10.60237917 10.42567684 10.53854438]
 [10.48672986 10.49989164 10.91745948 10.26287702 10.04969769]
 [10.46269203 10.40821902 10.48704348 10.07051578 10.58210861]
 [10.9870218  10.20908846 10.21237612 10.96113505 10.70695408]
 [10.59296821 10.38085241 10.6387405  10.50242857 10.08979307]]

[[-9.38676243 -9.70189835 -9.39762083 -9.57432316 -9.46145562]
 [-9.51327014 -9.50010836 -9.08254052 -9.73712298 -9.95030231]
 [-9.53730797 -9.59178098 -9.51295652 -9.92948422 -9.41789139]
 [-9.0129782  -9.79091154 -9.78762388 -9.03886495 -9.29304592]
 [-9.40703179 -9.61914759 -9.3612595  -9.49757143 -9.91020693]]

[[6.13237574 2.98101651 6.02379173 4.2567684  5.38544385]
 [4.86729857 4.99891638 9.17459483 2.62877022 0.49697686]
 [4.62692029 4.08219023 4.87043481 0.70515778 5.82108611]
 [9.87021798 2.09088456 2.12376118 9.6113505  7.06954075]
 [5.92968213 3.80852407 6.38740496 5.02428569 0.89793075]]

[[0.06132376 0.02981017 0.06023792 0.04256768 0.05385444]
 [0.04867299 0.0

In [51]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
x = np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [2,1,12], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[ 7 10  1]
[ 7 20  3]


### element-wise exponentiation

In [52]:
print(np.exp(arr))

[[1.84639959 1.34729874 1.8264591  1.53062606 1.71351083]
 [1.62698703 1.64854262 2.50292358 1.30066676 1.05095333]
 [1.5883441  1.50413657 1.62749737 1.0730615  1.78980846]
 [2.68323136 1.23255402 1.23661291 2.61466256 2.0278053 ]
 [1.80935099 1.46353158 1.89409376 1.65273017 1.09394789]]


### element-wise logorithm

In [53]:
# natural log ( base e )
print(np.log(arr)) 

[[-0.48900286 -1.21032074 -0.50686818 -0.85407481 -0.61888536]
 [-0.72004602 -0.69336393 -0.08614686 -1.33606895 -3.0017969 ]
 [-0.77069361 -0.89595143 -0.71940188 -2.65191879 -0.54109823]
 [-0.01306315 -1.56499788 -1.54939643 -0.03964035 -0.34678957]
 [-0.52261448 -0.96534336 -0.44825702 -0.6883018  -2.41024743]]


In [54]:
# base 2
print(np.log2(arr)) 
print()
# base 10
print(np.log10(arr))    

[[-0.705482   -1.74612373 -0.7312562  -1.2321695  -0.89286284]
 [-1.03880682 -1.0003127  -0.12428365 -1.92754005 -4.33067751]
 [-1.11187585 -1.29258468 -1.03787752 -3.82591008 -0.78063974]
 [-0.01884615 -2.25781468 -2.23530655 -0.05718894 -0.5003116 ]
 [-0.75397333 -1.39269608 -0.64669817 -0.99300959 -3.47725201]]

[[-0.21237124 -0.52563562 -0.22013005 -0.37091998 -0.2687785 ]
 [-0.31271201 -0.30112413 -0.03741311 -0.58024737 -1.30366383]
 [-0.33470798 -0.38910676 -0.31243227 -1.1517137  -0.23499598]
 [-0.00567326 -0.67966994 -0.67289432 -0.01721559 -0.1506088 ]
 [-0.22696859 -0.4192433  -0.19467555 -0.29892567 -1.04675716]]


### element-wise square root

In [55]:
print(np.sqrt(arr))

[[0.78309487 0.54598686 0.7761309  0.65243915 0.73385583]
 [0.69766027 0.70703015 0.95784105 0.51271534 0.22292978]
 [0.68021469 0.6389202  0.69788501 0.26554807 0.76296043]
 [0.99348971 0.45726191 0.46084283 0.98037495 0.84080561]
 [0.77004429 0.61713241 0.79921242 0.70882196 0.29965493]]


### element-wise sine and cosine

In [56]:
print(np.sin(arr))
print()
print(np.cos(arr))

[[0.57551812 0.29370611 0.56660449 0.41293731 0.51288695]
 [0.46773802 0.47933044 0.79405996 0.25985981 0.04967723]
 [0.4463587  0.39697533 0.4680152  0.07045735 0.54978649]
 [0.83438816 0.2075683  0.21078323 0.81984201 0.64952084]
 [0.55882498 0.37171193 0.59618473 0.48155539 0.08967246]]

[[0.81778902 0.95589577 0.8239899  0.91075945 0.85845616]
 [0.88386715 0.87763451 0.60783944 0.96564635 0.99876532]
 [0.89485413 0.91782928 0.88372041 0.99751479 0.83530522]
 [0.55117728 0.97822053 0.97753283 0.57258979 0.76034379]
 [0.82928562 0.92834812 0.80284729 0.87641566 0.99597131]]


### sum along a specified axis

In [57]:
# sum along the row
print(np.sum(arr, axis=0)) 

[3.14264947 1.79615318 2.85799875 2.22263326 1.96709783]


In [58]:
# sum along the column
print(np.sum(arr, axis=1)) 

[2.47793962 2.21665569 2.01057892 3.0765755  2.20478276]


In [59]:
print(np.sum(arr))

11.98653248889483


### compute the min and max along a specified axis

In [60]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.46269203 0.20908846 0.21237612 0.07051578 0.04969769]


In [61]:
# calculate max along the column
print(np.max(arr, axis=1))   

[0.61323757 0.91745948 0.58210861 0.9870218  0.6387405 ]


In [62]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9870217983557753
0.049697686154183573


### compute element-wise min and max of two arrays

In [63]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[1 4 5 8 9]

[0 3 3 7 7]


### compute the mean

In [64]:
# compute the overall mean
print(np.mean(arr))
print()
# compute the mean along the row
print(np.mean(arr, axis=0))   
print()
# compute the mean along the column
print(np.mean(arr, axis=1)) 

0.47946129955579325

[0.62852989 0.35923064 0.57159975 0.44452665 0.39341957]

[0.49558792 0.44333114 0.40211578 0.6153151  0.44095655]


### compute the median

In [65]:
# compute the overall median
x = [1,2,4,6,7,8,9,12, 20]
print(np.median(x))
print()
# compute the median along the row
print(np.median(arr, axis=0)) 
print()
# compute the median along the column
print(np.median(arr, axis=1))

7.0

[0.59296821 0.38085241 0.60237917 0.42567684 0.53854438]

[0.53854438 0.48672986 0.46269203 0.70695408 0.50242857]


### compute the standard deviation & variance

In [66]:
# compute the overall standard deviation
print(np.std(arr))
print()

# compute the standard deviation along the row
print(np.std(arr, axis=0))
print()

# compute the standard deviation along the column
print(np.std(arr, axis=1))
print()

# compute the overall variance
print(np.var(arr))
print()

# compute the variance along the row
print(np.var(arr, axis=0))
print()

# compute the variance along the column
print(np.var(arr, axis=1))

0.25024367544311055

[0.18848044 0.09892655 0.22858941 0.29781635 0.27029703]

[0.11914651 0.28892601 0.17508594 0.3445388  0.19643479]

0.06262189709927685

[0.03552488 0.00978646 0.05225312 0.08869458 0.07306049]

[0.01419589 0.08347824 0.03065509 0.11870698 0.03858663]


### compute the covariance & correlation

In [67]:
arr = np.random.rand(5,8)
arr

array([[0.29717467, 0.82814423, 0.17545597, 0.90448946, 0.58831483,
        0.01653446, 0.37002218, 0.0421295 ],
       [0.12728055, 0.17926823, 0.16645859, 0.8836885 , 0.90595205,
        0.23540098, 0.40725992, 0.47116016],
       [0.83023402, 0.29200762, 0.17382853, 0.45814311, 0.90242916,
        0.59493692, 0.41261333, 0.40565094],
       [0.30848417, 0.31787873, 0.41508602, 0.63816707, 0.79526952,
        0.03703341, 0.7345411 , 0.77257086],
       [0.24442453, 0.98507686, 0.67500584, 0.89276474, 0.2430547 ,
        0.05169588, 0.70974306, 0.95726431]])

In [68]:
print(np.cov(arr))

[[ 0.11574664  0.05174499  0.00066924  0.02271365  0.04918467]
 [ 0.05174499  0.0994141   0.0272675   0.06076657  0.01040574]
 [ 0.00066924  0.0272675   0.06390655  0.0035774  -0.06755352]
 [ 0.02271365  0.06076657  0.0035774   0.07527547  0.04338815]
 [ 0.04918467  0.01040574 -0.06755352  0.04338815  0.13336772]]


In [69]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.23123571]
 [-0.23123571  1.        ]]


### flatten an array

In [70]:
# return a copy
new = arr.flatten()
new.ndim # number of dimensions

1

### append elements to an array

In [71]:
arr = np.array([1,2,3])

In [72]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [73]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [74]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


In [75]:
arr

array([1, 2, 3])

### delete elements from an array

In [76]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [77]:
arr

array([1, 2, 3])

In [78]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [79]:
arr = np.array([1,2,3])
arrx = arr

In [80]:
arrx

array([1, 2, 3])

In [81]:
arrx[0] = 7

In [82]:
arrx

array([7, 2, 3])

In [83]:
arr

array([7, 2, 3])

In [84]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
a = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

### select the unique elements from an array

In [85]:
arr = np.array([7,1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6 7]


In [86]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)

#print(type(uniques))
print(uniques)
#print(type(counts))
print(counts)

x = int(counts[0])
type(x)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


int

### compute the intersection & union of two arrays

In [87]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [110]:
# intersection
print(np.intersect1d(arr1, arr2))
print(type(np.intersect1d(arr1, arr2)))

[3 4 5]
<class 'numpy.ndarray'>


In [111]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### matrix multiplication

In [112]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [113]:
print(arr1.dot(arr2))
# or
print()
print(np.dot(arr1, arr2))
# or
print()
print(arr1 @ arr2)

[[0.95057457 0.40856616 1.44212067 2.40513229 1.28615131]
 [0.49533675 0.26168434 0.70680314 1.04659659 0.65428328]
 [0.83005333 0.6187268  1.06830471 1.24234934 0.92233042]
 [1.00761048 0.68858699 1.36286153 1.20077629 0.72945073]
 [0.94683847 0.58248303 1.38169162 1.25852082 0.70268079]]

[[0.95057457 0.40856616 1.44212067 2.40513229 1.28615131]
 [0.49533675 0.26168434 0.70680314 1.04659659 0.65428328]
 [0.83005333 0.6187268  1.06830471 1.24234934 0.92233042]
 [1.00761048 0.68858699 1.36286153 1.20077629 0.72945073]
 [0.94683847 0.58248303 1.38169162 1.25852082 0.70268079]]

[[0.95057457 0.40856616 1.44212067 2.40513229 1.28615131]
 [0.49533675 0.26168434 0.70680314 1.04659659 0.65428328]
 [0.83005333 0.6187268  1.06830471 1.24234934 0.92233042]
 [1.00761048 0.68858699 1.36286153 1.20077629 0.72945073]
 [0.94683847 0.58248303 1.38169162 1.25852082 0.70268079]]


### QR factorization 

In [114]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.09622843 -0.89025753  0.38954626 -0.21103773 -0.04357079]
 [-0.22230932 -0.32171075 -0.89892325 -0.18880203 -0.05806507]
 [-0.29822747 -0.03619589  0.03109339  0.51208206 -0.80408669]
 [-0.82726399  0.28010025  0.19665835 -0.44516068  0.01831935]
 [-0.40989427 -0.15549096 -0.02343943  0.67780588  0.5897788 ]]
[[-1.18357002 -1.17301661 -1.1617491  -0.73561589 -0.54956419]
 [ 0.         -0.69734011 -0.2097282  -0.22361172 -0.83005133]
 [ 0.          0.          0.35506797  0.22551206 -0.17120902]
 [ 0.          0.          0.          0.1455672  -0.11438042]
 [ 0.          0.          0.          0.         -0.05080715]]


### singular value decomposition (SVD)

In [115]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.28521226  0.49242084 -0.11388864  0.50707814 -0.63724156]
 [-0.37424789  0.70912588  0.28542941 -0.3805851   0.3616131 ]
 [-0.51106128 -0.31721935  0.420393    0.57318299  0.3645809 ]
 [-0.42084046 -0.35887229  0.37556595 -0.49797427 -0.5523367 ]
 [-0.58335423 -0.158886   -0.76666771 -0.14666157  0.15863194]]
[2.65594755 0.82191855 0.65260336 0.28568907 0.18451305]
[[-0.36068989 -0.551207   -0.52802466 -0.42242109 -0.32988487]
 [-0.24357934  0.54568907 -0.64080842 -0.07485547  0.47608169]
 [ 0.5518233   0.44836702 -0.16838185 -0.43455712 -0.52656027]
 [-0.68416616  0.40765615  0.450771   -0.30885832 -0.25912387]
 [-0.19488359  0.17657227 -0.28108288  0.72919389 -0.56578379]]


### singular value decomposition (SVD)

In [116]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.31686022+0.j         -0.17032014+0.12798729j -0.17032014-0.12798729j
  0.43636165+0.j          0.15802984+0.j        ]


### eigen value decomposition

In [117]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.47577352+0.j          0.04077632+0.38863468j  0.04077632-0.38863468j
  0.43594429+0.j         -0.34408391+0.j        ]
[[ 0.44950894+0.j          0.04296794-0.48818043j  0.04296794+0.48818043j
  -0.74644634+0.j         -0.15840563+0.j        ]
 [ 0.2533776 +0.j         -0.68668626+0.j         -0.68668626-0.j
  -0.1983513 +0.j          0.65003321+0.j        ]
 [ 0.59556014+0.j          0.11618178+0.28440424j  0.11618178-0.28440424j
  -0.1178561 +0.j         -0.44353153+0.j        ]
 [ 0.33890281+0.j          0.0957586 +0.0514196j   0.0957586 -0.0514196j
   0.56020634+0.j         -0.31796547+0.j        ]
 [ 0.51399856+0.j          0.36257111+0.2250336j   0.36257111-0.2250336j
   0.27523337+0.j          0.50452178+0.j        ]]


### compute the trace & determinant

In [118]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

2.6491865477385


In [119]:
print(np.linalg.det(arr))

-0.05670798976932483


### calculate the inverse/psedo-inverse of a matrix

In [120]:
arr = np.random.rand(5,5)

In [121]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-29.88815725 -21.35244617  21.21393916   8.90443286  21.17341987]
 [ -1.09588936  -0.43614301   0.66801176   1.83856832  -0.14769201]
 [  1.70282007   0.53451669   0.0647178   -1.22701333  -0.55787687]
 [ -8.60413359  -3.34629845   6.34372866   3.0524389    3.39874278]
 [ 29.96453811  19.61494736 -22.49306021  -9.61254243 -17.70969393]]


In [122]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[-29.88815725 -21.35244617  21.21393916   8.90443286  21.17341987]
 [ -1.09588936  -0.43614301   0.66801176   1.83856832  -0.14769201]
 [  1.70282007   0.53451669   0.0647178   -1.22701333  -0.55787687]
 [ -8.60413359  -3.34629845   6.34372866   3.0524389    3.39874278]
 [ 29.96453811  19.61494736 -22.49306021  -9.61254243 -17.70969393]]
